# Loading model from state dict

### Import libraries

In [18]:
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
from torch.nn import functional as F

### Define model class
* Loading from state dict requires the class defintion as well as a model object to be present in the script.
* save the state_dict rather than the model to be robust to changes in your environment

In [19]:
input_size = 13
output_size = 3
hidden_size = 100

In [20]:
class Net1(nn.Module):
    
    def __init__(self):
        super(Net1, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, output_size)

    def forward(self, X):
        X = torch.sigmoid((self.fc1(X)))
        X = torch.sigmoid(self.fc2(X))
        X = self.fc3(X)

        return F.log_softmax(X, dim=-1)

In [21]:
model = Net1()

In [22]:
model.load_state_dict(torch.load('models/classifier_state_dict_'))

In [23]:
model.eval()

Net1(
  (fc1): Linear(in_features=13, out_features=100, bias=True)
  (fc2): Linear(in_features=100, out_features=100, bias=True)
  (fc3): Linear(in_features=100, out_features=3, bias=True)
)

## Run predictions on the loaded model

In [24]:
test_df = pd.read_csv("data/wine_test_data.csv")

In [25]:
test_df

Class  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0      0    14.23        1.71  2.43               15.6        127   
1      1    11.65        1.67  2.62               26.0         88   
2      0    14.37        1.95  2.50               16.8        113   
3      2    13.27        4.28  2.26               20.0        120   
4      2    12.82        3.37  2.30               19.5         88   
5      0    12.93        3.80  2.65               18.6        102   
6      1    11.84        2.89  2.23               18.0        112   
7      2    13.17        2.59  2.37               20.0        120   
8      1    11.41        0.74  2.50               21.0         88   
9      1    12.08        1.33  2.30               23.6         70   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           1.92        1.61                  0.40             1.34   
2           3.85        3.49                  0.24             2.18   
3           1.59        0.69                  0.43             1.35   
4           1.48        0.66                  0.40             0.97   
5           2.41        2.41                  0.25             1.98   
6           1.72        1.32                  0.43             0.95   
7           1.65        0.68                  0.53             1.46   
8           2.48        2.01                  0.42             1.44   
9           2.20        1.59                  0.42             1.38   

   Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0             5.64  1.04                          3.92     1065  
1             2.60  1.36                          3.21      562  
2             7.80  0.86                          3.45     1480  
3            10.20  0.59                          1.56      835  
4            10.26  0.72                          1.75      685  
5             4.50  1.03                          3.52      770  
6             2.65  0.96                          2.52      500  
7             9.30  0.60                          1.62      840  
8             3.08  1.10                          2.31      434  
9             1.74  1.07                          3.21      625

In [26]:
x_test = test_df.drop('Class', axis = 1)
y_test = test_df['Class']

#### Converting the features to a numpy array and then a tensor

In [27]:
sample = np.array(x_test)

sample_tensor = torch.from_numpy(sample).float()

In [28]:
sample_tensor

tensor([[1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03],
        [1.1650e+01, 1.6700e+00, 2.6200e+00, 2.6000e+01, 8.8000e+01, 1.9200e+00,
         1.6100e+00, 4.0000e-01, 1.3400e+00, 2.6000e+00, 1.3600e+00, 3.2100e+00,
         5.6200e+02],
        [1.4370e+01, 1.9500e+00, 2.5000e+00, 1.6800e+01, 1.1300e+02, 3.8500e+00,
         3.4900e+00, 2.4000e-01, 2.1800e+00, 7.8000e+00, 8.6000e-01, 3.4500e+00,
         1.4800e+03],
        [1.3270e+01, 4.2800e+00, 2.2600e+00, 2.0000e+01, 1.2000e+02, 1.5900e+00,
         6.9000e-01, 4.3000e-01, 1.3500e+00, 1.0200e+01, 5.9000e-01, 1.5600e+00,
         8.3500e+02],
        [1.2820e+01, 3.3700e+00, 2.3000e+00, 1.9500e+01, 8.8000e+01, 1.4800e+00,
         6.6000e-01, 4.0000e-01, 9.7000e-01, 1.0260e+01, 7.2000e-01, 1.7500e+00,
         6.8500e+02],
        [1.2930e+01, 3.8000e+00, 2.6500e+00, 1.8600e+01, 1.0200e+02, 2.4100e+00,

In [29]:
out = model(sample_tensor)
out

tensor([[-3.7670e-05, -1.0222e+01, -1.3527e+01],
        [-3.2600e+00, -3.9166e-02, -1.0889e+01],
        [-4.7226e-03, -1.8158e+01, -5.3578e+00],
        [-5.6075e+00, -1.3569e+01, -3.6783e-03],
        [-5.6067e+00, -1.3569e+01, -3.6812e-03],
        [-4.7892e-01, -9.8946e-01, -4.7362e+00],
        [-2.2026e+00, -1.1727e-01, -8.8794e+00],
        [-5.6072e+00, -1.3568e+01, -3.6793e-03],
        [-3.2403e+00, -3.9960e-02, -1.0853e+01],
        [-3.2695e+00, -3.8787e-02, -1.0908e+01]], grad_fn=<LogSoftmaxBackward>)

#### Picking target with the highest probability

In [30]:
_, predicted = torch.max(out.data, -1)

In [31]:
predicted

tensor([0, 1, 0, 2, 2, 0, 1, 2, 1, 1])

In [32]:
predicted_df = pd.DataFrame(data = predicted.numpy(), columns = ['Predicted Class'])

In [33]:
compare = [predicted_df, y_test]
comapare_df = pd.concat(compare, axis=1)

In [34]:
comapare_df

Predicted Class  Class
0                0      0
1                1      1
2                0      0
3                2      2
4                2      2
5                0      0
6                1      1
7                2      2
8                1      1
9                1      1